# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TransformationPipe": "00_pipes.ipynb"}

modules = ["pipes.py"]

doc_url = "https://robtheoceanographer.github.io/pypipe/"

git_url = "https://github.com/robtheoceanographer/pypipe/tree/master/"

def custom_doc_links(name): return None
